name: CI on push to branch
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
jobs:
  run-unittests:
    name: Run unittests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/CI_push.yml
      - name: Install test dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "flit>=3.4,<4"
          flit install --only-deps --deps=production --extras=test
      - name: Run unittests via pytest
        run: pytest -vv -m "not endtoend and not singularity_integration and not conda_integration"
